Clothy/Entities/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clothy.Entities
{
    public class Item
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public string Sizes { get; set; }
        public string Picture { get; set; }
        public Guid CategoryId { get; set; }
        public IList<User> Carts { get; set; }

        public Item()
        {

        }

        public Item(string name, double price, string description, string sizes, string picture, Guid catId)
        {
            Id = Guid.NewGuid();
            Name = name;
            Price = price;
            Description = description;
            Sizes = sizes;
            Picture = picture;
            CategoryId = catId;

            Carts = new List<User>();
        }

        // override object.Equals
        public override bool Equals(object obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }

            return ((Item)obj).Id.Equals(Id);
        }

        // override object.GetHashCode
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}

Clothy/Models/ClothyViewModels/ItemViewModel.cs
using Clothy.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clothy.Models.ClothyViewModels
{
    public class ItemViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public string Sizes { get; set; }
        public string Picture { get; set; }
        public Guid CategoryId { get; set; }
        public bool IsAdmin { get; set; }
    }
}

Clothy/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Clothy.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Clothy.Models;
using Clothy.Models.ClothyViewModels;

namespace Clothy.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUserRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;

        public CartController(
            IUserRepository repository, 
            UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Preview()
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            CartViewModel model = new CartViewModel(
                (await _repository.GetItemsFromCart(currentUser.Id))
                .Select(i => new CartItemViewModel()
                {
                    Id = i.Id,
                    Name = i.Name,
                    Price = i.Price
                }).ToList());

            return View(model);
        }

        public async Task<IActionResult> RemoveFromCart(Guid itemId)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            await _repository.RemoveFromCart(currentUser.Id, itemId);

            return RedirectToAction("Preview");
        }

        public async Task<IActionResult> AddToCart(Guid itemId)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            await _repository.AddToCart(currentUser.Id, itemId);

            return RedirectToAction("Preview");
        }
    }
}

Clothy/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Clothy.Models.ClothyViewModels;
using Clothy.Entities;
using Clothy.Repositories;
using Microsoft.AspNetCore.Identity;
using Clothy.Models;
using Microsoft.AspNetCore.Authorization;

namespace Clothy.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemRepository _repository;

        public ItemController(IItemRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Preview(Guid itemId)
        {
            Item target = await _repository.GetItemById(itemId);

            ItemViewModel model = new ItemViewModel()
            {
                Id = target.Id,
                Name = target.Name,
                Price = target.Price,
                Description = target.Description,
                Sizes = target.Sizes,
                Picture = target.Picture,
                CategoryId = target.CategoryId
            };

            return View(model);
        }

        public async Task<IActionResult> Categorize(Guid catId)
        {
            ListItemViewModel model = new ListItemViewModel(
                (await _repository.GetItemsByCategoryId(catId))
                .Select(i => new ItemViewModel()
                {
                    Id = i.Id,
                    Name = i.Name,
                    Price = i.Price,
                    Description = i.Description,
                    Sizes = i.Sizes,
                    Picture = i.Picture,
                    CategoryId = i.CategoryId,
                    IsAdmin = false
                }).ToList());

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> List()
        {
            ListItemViewModel model = new ListItemViewModel(
                (await _repository.GetAllItems())
                .Select(i => new ItemViewModel()
                {
                    Id = i.Id,
                    Name = i.Name,
                    Price = i.Price,
                    Description = i.Description,
                    Sizes = i.Sizes,
                    Picture = i.Picture,
                    CategoryId = i.CategoryId,
                    IsAdmin = true
                }).ToList());

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Manage()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid itemId)
        {
            Item target = await _repository.GetItemById(itemId);

            AddItemViewModel model = new AddItemViewModel()
            {
                Id = target.Id,
                Name = target.Name,
                Price = target.Price,
                Description = target.Description,
                Sizes = target.Sizes,
                Picture = target.Picture,
                CategoryId = target.CategoryId
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(AddItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            Item target = new Item
            {
                Id = model.Id,
                Name = model.Name,
                Price = model.Price,
                Description = model.Description,
                Sizes = model.Sizes,
                Picture = model.Picture,
                CategoryId = model.CategoryId
            };

            await _repository.EditItem(target);

            return RedirectToAction("List");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Remove(Guid itemId)
        {
            await _repository.RemoveItem(itemId);

            return RedirectToAction("List");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Add(AddItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", model);
            }

            Item target = new Item(
                model.Name,
                model.Price,
                model.Description,
                model.Sizes,
                model.Picture,
                model.CategoryId);

            await _repository.AddItem(target);

            return RedirectToAction("Manage");
        }
    }
}

Clothy/ViewComponents/CategoryListViewComponent.cs
using Clothy.Data;
using Clothy.Entities;
using Clothy.Models.ClothyViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;

namespace Clothy.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly ClothyDbContext _context;

        public CategoryListViewComponent(ClothyDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string view)
        {
            CategoryListViewModel model = new CategoryListViewModel(
                (await GetAllCategories())
                .Select(i => new CategoryViewModel()
                {
                    Id = i.Id,
                    Name = i.Name,
                }).ToList());

            return View(view, model);
        }

        public Task<List<Category>> GetAllCategories()
        {
            return _context.Categories.OrderBy(c => c.Name)
                                      .ToListAsync();
        }
    }
}

Clothy/Views/Item/Add.cshtml
@model Clothy.Models.ClothyViewModels.AddItemViewModel

<h4 style="margin-top: 30px">Add new item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Item" asp-action="Add" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" type="number" min="0.01" step="0.01" class="form-control" placeholder="in €" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sizes" class="control-label"></label>
                <input asp-for="Sizes" class="form-control" placeholder="e.g. S,L,M,39,40,42" />
                <span asp-validation-for="Sizes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" placeholder="link to picture online" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category</label>
                <select asp-for="CategoryId" class="form-control">
                    <option disabled selected>Category</option>
                    @await Component.InvokeAsync("CategoryList", new { view = "Pick" })
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Item" asp-action="Manage">Return</a>
</div>

Clothy/Views/Item/Categorize.cshtml
@model Clothy.Models.ClothyViewModels.ListItemViewModel

<div>
    @foreach (var itemModel in Model.Models)
    {
        @Html.Partial("_ShowItemPartial", itemModel);

    }
</div>

Clothy/Views/Item/Edit.cshtml
@model Clothy.Models.ClothyViewModels.AddItemViewModel

<h4>Edit item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" type="number" min="0.01" step="0.01" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sizes" class="control-label"></label>
                <input asp-for="Sizes" class="form-control" />
                <span asp-validation-for="Sizes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category</label>
                <select asp-for="CategoryId" class="form-control">
                    <option disabled selected>Category</option>
                    @await Component.InvokeAsync("CategoryList", new { view = "Pick" })
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Return</a>
</div>

Clothy/Views/Item/List.cshtml
@model Clothy.Models.ClothyViewModels.ListItemViewModel

<div>
    @foreach (var itemModel in Model.Models)
    {
        @Html.Partial("_ShowItemPartial", itemModel);

    }
</div>

<div style="margin-top: 20px">
    <a asp-controller="Item" asp-action="Manage">Return</a>
</div>

Clothy/Views/Item/Manage.cshtml
<h4 style="margin-top: 30px">Manage items</h4>

<div style="margin-top: 30px" id="link-div-custom">
    <a asp-controller="Item" asp-action="Add">Add new Item</a>
    <br />
    <a asp-controller="Item" asp-action="List">Show all items</a>
</div>

Clothy/Views/Item/Preview.cshtml
@model Clothy.Models.ClothyViewModels.ItemViewModel

<div>
    <h4>Preview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <img src="@Model.Picture" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price) €
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sizes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sizes)
        </dd>
    </dl>
</div>

<div>
    <a asp-controller="Cart" asp-action="AddToCart" asp-route-itemId="@Model.Id">Add to cart</a>
</div>

<div>
    <a asp-controller="Item" asp-action="Categorize" asp-route-catId="@Model.CategoryId">Return</a>
</div>