Clothy/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Clothy.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Clothy.Models;
using Clothy.Models.ClothyViewModels;

namespace Clothy.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUserRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;

        public CartController(
            IUserRepository repository, 
            UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Preview()
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            CartViewModel model = new CartViewModel(
                (await _repository.GetItemsFromCart(currentUser.Id))
                .Select(i => new CartItemViewModel()
                {
                    Id = i.Id,
                    Name = i.Name,
                    Price = i.Price
                }).ToList());

            return View(model);
        }

        public async Task<IActionResult> RemoveFromCart(Guid itemId)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            await _repository.RemoveFromCart(currentUser.Id, itemId);

            return RedirectToAction("Preview");
        }

        public async Task<IActionResult> AddToCart(Guid itemId)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            await _repository.AddToCart(currentUser.Id, itemId);

            return RedirectToAction("Preview");
        }
    }
}

Clothy/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Clothy.Models.ClothyViewModels;
using Clothy.Entities;
using Clothy.Repositories;
using Microsoft.AspNetCore.Identity;
using Clothy.Models;
using Microsoft.AspNetCore.Authorization;

namespace Clothy.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _repository;

        public CategoryController(ICategoryRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Manage()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        public async Task<IActionResult> Edit(Guid catId)
        {
            Category target = await _repository.GetCategoryById(catId);

            AddCategoryViewModel model = new AddCategoryViewModel()
            {
                Id = target.Id,
                Name = target.Name,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AddCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            Category target = new Category
            {
                Id = model.Id,
                Name = model.Name,
            };

            await _repository.EditCategory(target);

            return RedirectToAction("List");
        }

        public async Task<IActionResult> List()
        {
            CategoryListViewModel model = new CategoryListViewModel(
                (await _repository.GetAllCategories())
                .Select(i => new CategoryViewModel()
                {
                    Id = i.Id,
                    Name = i.Name
                }).ToList());

            return View(model);
        }

        public async Task<IActionResult> Remove(Guid catId)
        {
            await _repository.RemoveCategory(catId);

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", model);
            }

            Category target = new Category(model.Name);

            await _repository.AddCategory(target);

            return RedirectToAction("Manage");
        }
    }
}

Clothy/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Clothy.Models.ClothyViewModels;
using Clothy.Entities;
using Clothy.Repositories;
using Microsoft.AspNetCore.Identity;
using Clothy.Models;
using Microsoft.AspNetCore.Authorization;

namespace Clothy.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemRepository _repository;

        public ItemController(IItemRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Preview(Guid itemId)
        {
            Item target = await _repository.GetItemById(itemId);

            ItemViewModel model = new ItemViewModel()
            {
                Id = target.Id,
                Name = target.Name,
                Price = target.Price,
                Description = target.Description,
                Sizes = target.Sizes,
                Picture = target.Picture,
                CategoryId = target.CategoryId
            };

            return View(model);
        }

        public async Task<IActionResult> Categorize(Guid catId)
        {
            ListItemViewModel model = new ListItemViewModel(
                (await _repository.GetItemsByCategoryId(catId))
                .Select(i => new ItemViewModel()
                {
                    Id = i.Id,
                    Name = i.Name,
                    Price = i.Price,
                    Description = i.Description,
                    Sizes = i.Sizes,
                    Picture = i.Picture,
                    CategoryId = i.CategoryId,
                    IsAdmin = false
                }).ToList());

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> List()
        {
            ListItemViewModel model = new ListItemViewModel(
                (await _repository.GetAllItems())
                .Select(i => new ItemViewModel()
                {
                    Id = i.Id,
                    Name = i.Name,
                    Price = i.Price,
                    Description = i.Description,
                    Sizes = i.Sizes,
                    Picture = i.Picture,
                    CategoryId = i.CategoryId,
                    IsAdmin = true
                }).ToList());

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Manage()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid itemId)
        {
            Item target = await _repository.GetItemById(itemId);

            AddItemViewModel model = new AddItemViewModel()
            {
                Id = target.Id,
                Name = target.Name,
                Price = target.Price,
                Description = target.Description,
                Sizes = target.Sizes,
                Picture = target.Picture,
                CategoryId = target.CategoryId
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(AddItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            Item target = new Item
            {
                Id = model.Id,
                Name = model.Name,
                Price = model.Price,
                Description = model.Description,
                Sizes = model.Sizes,
                Picture = model.Picture,
                CategoryId = model.CategoryId
            };

            await _repository.EditItem(target);

            return RedirectToAction("List");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Remove(Guid itemId)
        {
            await _repository.RemoveItem(itemId);

            return RedirectToAction("List");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Add(AddItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", model);
            }

            Item target = new Item(
                model.Name,
                model.Price,
                model.Description,
                model.Sizes,
                model.Picture,
                model.CategoryId);

            await _repository.AddItem(target);

            return RedirectToAction("Manage");
        }
    }
}

Clothy/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Clothy.Repositories;
using Clothy.Models.ClothyViewModels;
using Clothy.Entities;
using Microsoft.AspNetCore.Identity;
using Clothy.Models;

namespace Clothy.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _repository;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrderController(
            IOrderRepository repository, 
            UserManager<ApplicationUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        public IActionResult MakeOrder()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MakeOrder(MakeOrderViewModel model)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(HttpContext.User);

            if (!ModelState.IsValid)
            {
                return View("MakeOrder", model);
            }

            Order target = new Order(
                currentUser.Id,
                model.Mail,
                model.Phone,
                model.Address);

            await _repository.MakeOrder(target);

            return View("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ShowOrders()
        {
            OrderListViewModel model = new OrderListViewModel(
                (await _repository.GetAllOrders())
                .Select(o => new OrderViewModel()
                {
                    Id = o.Id,
                    Mail = o.Mail,
                    Phone = o.Phone,
                    Address = o.Address,
                    DateCreated = o.DateCreated
                }).ToList());

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Manage()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Clothy/Views/Shared/_CartItemPartial.cshtml
@model Clothy.Models.ClothyViewModels.CartItemViewModel

<div>
    <span style="margin-right: 10px"><strong>@Model.Name</strong></span>
    <span style="margin-right: 10px">@Model.Price €</span>
    <span>
        <a asp-controller="Cart" asp-action="RemoveFromCart" asp-route-itemId="@Model.Id">Remove</a>
    </span>
</div>

Clothy/Views/Shared/_Layout.cshtml
@using Clothy.ViewComponents

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clothy</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-first">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Clothy</a>
            </div>
            <div class="navbar-collapse collapse nav-first">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Item" asp-action="Manage">Manage items</a></li>
                    <li><a asp-area="" asp-controller="Category" asp-action="Manage">Manage categories</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Manage">Manage orders</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    
    @await Component.InvokeAsync("CategoryList", new { view = "Navbar" })

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Clothy</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Clothy/Views/Shared/_ShowCategoryPartial.cshtml
@model Clothy.Models.ClothyViewModels.CategoryViewModel

<div>
    <span><strong>@Model.Name</strong></span>
    <a asp-controller="Category" asp-action="Edit" asp-route-catId="@Model.Id">Edit</a>
    <span> | </span>
    <a asp-controller="Category" asp-action="Remove" asp-route-catId="@Model.Id">Remove</a>
</div>

Clothy/Views/Shared/_ShowItemPartial.cshtml
@model Clothy.Models.ClothyViewModels.ItemViewModel

<div style="border: 1px solid black; width: 202px; float: left; margin: 5px 5px 5px 5px">
    <img style="width: 200px; height: 200px" src="@Model.Picture" />
    <div><strong>@Model.Name</strong></div>
    <div>@Model.Price €</div>
    <div>
        <a asp-controller="Item" asp-action="Preview" asp-route-itemId="@Model.Id">Details</a>
    </div>
    @if (Model.IsAdmin)
    {
        <a asp-controller="Item" asp-action="Edit" asp-route-itemId="@Model.Id">Edit</a>
        <span> | </span>
        <a asp-controller="Item" asp-action="Remove" asp-route-itemId="@Model.Id">Remove</a>
    }
</div>

Clothy/Views/Shared/_ShowOrderPartial.cshtml
@model Clothy.Models.ClothyViewModels.OrderViewModel

<div>
    <span style="margin-right: 10px">@Model.Address</span>
    <span style="margin-right: 10px">@Model.Phone</span>
    <span style="margin-right: 10px">@Model.Mail</span>
    <span style="margin-right: 10px">@Model.DateCreated</span>
</div>